# Generated by Django 4.2.1 on 2024-03-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='robot',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='robots.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='robot',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='robots.tagpost', verbose_name='Тэги'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['-time_create'], name='robots_robo_time_cr_67e8c9_idx'),
        ),
    ]
