# Generated by Django 4.2.1 on 2024-03-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_alter_robot_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
