# Generated by Django 4.2.1 on 2024-03-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_category_robot_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robots.category'),
        ),
    ]
